image: debian:buster-slim

build:
  stage: build
  # install the necessary build tools when needed
  before_script:
     - dpkg --add-architecture i386
     - apt-get update
     - apt-get -y --no-install-recommends install gcc-mingw-w64-i686 g++-mingw-w64-i686 make cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/mingw_crash_handler.dll
